# Generated by Django 3.2.8 on 2021-10-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostalgia_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='details',
            new_name='detail',
        ),
    ]
